"""initial schema

Revision ID: 75fdf91a7553
Revises: 
Create Date: 2026-03-08 23:29:56.210658
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75fdf91a7553'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocos_parlamentares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('casa', sa.Enum('CAMARA', 'SENADO', name='casa'), nullable=False),
    sa.Column('legislatura', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('dados_brutos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla')
    )
    op.create_table('proposicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_externo', sa.String(length=50), nullable=False),
    sa.Column('casa_origem', sa.Enum('CAMARA', 'SENADO', name='casa'), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('ementa', sa.Text(), nullable=False),
    sa.Column('ementa_simplificada', sa.Text(), nullable=True),
    sa.Column('resumo_cidadao', sa.Text(), nullable=True),
    sa.Column('url_inteiro_teor', sa.String(length=500), nullable=True),
    sa.Column('situacao', sa.String(length=100), nullable=True),
    sa.Column('relevancia_score', sa.Float(), nullable=True),
    sa.Column('dados_brutos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposicoes_id_externo'), 'proposicoes', ['id_externo'], unique=True)
    op.create_table('topicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('icone', sa.String(length=10), nullable=True),
    sa.Column('cor', sa.String(length=7), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('senha_hash', sa.String(length=200), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('anonimo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bloco_partido',
    sa.Column('bloco_id', sa.Integer(), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bloco_id'], ['blocos_parlamentares.id'], ),
    sa.ForeignKeyConstraint(['partido_id'], ['partidos.id'], ),
    sa.PrimaryKeyConstraint('bloco_id', 'partido_id')
    )
    op.create_table('parlamentares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_externo', sa.String(length=50), nullable=False),
    sa.Column('casa', sa.Enum('CAMARA', 'SENADO', name='casa'), nullable=False),
    sa.Column('nome_civil', sa.String(length=200), nullable=False),
    sa.Column('nome_parlamentar', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('partido_id', sa.Integer(), nullable=True),
    sa.Column('legislatura_atual', sa.Boolean(), nullable=False),
    sa.Column('dados_brutos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partido_id'], ['partidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parlamentares_id_externo'), 'parlamentares', ['id_externo'], unique=True)
    op.create_table('proposicoes_topicos',
    sa.Column('proposicao_id', sa.Integer(), nullable=False),
    sa.Column('topico_id', sa.Integer(), nullable=False),
    sa.Column('confianca', sa.Float(), nullable=False),
    sa.Column('metodo', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['proposicao_id'], ['proposicoes.id'], ),
    sa.ForeignKeyConstraint(['topico_id'], ['topicos.id'], ),
    sa.PrimaryKeyConstraint('proposicao_id', 'topico_id')
    )
    op.create_table('respostas_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('proposicao_id', sa.Integer(), nullable=False),
    sa.Column('voto', sa.Enum('SIM', 'NAO', 'PULAR', name='votousuario'), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposicao_id'], ['proposicoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'proposicao_id', name='uq_resposta_usuario')
    )
    op.create_index(op.f('ix_respostas_usuarios_usuario_id'), 'respostas_usuarios', ['usuario_id'], unique=False)
    op.create_table('votacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_externo', sa.String(length=50), nullable=False),
    sa.Column('proposicao_id', sa.Integer(), nullable=True),
    sa.Column('casa', sa.Enum('CAMARA', 'SENADO', name='casa'), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('resultado', sa.String(length=50), nullable=True),
    sa.Column('total_sim', sa.Integer(), nullable=False),
    sa.Column('total_nao', sa.Integer(), nullable=False),
    sa.Column('total_abstencao', sa.Integer(), nullable=False),
    sa.Column('total_ausente', sa.Integer(), nullable=True),
    sa.Column('dados_brutos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposicao_id'], ['proposicoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votacoes_id_externo'), 'votacoes', ['id_externo'], unique=True)
    op.create_table('votos_parlamentares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('votacao_id', sa.Integer(), nullable=False),
    sa.Column('parlamentar_id', sa.Integer(), nullable=False),
    sa.Column('voto', sa.Enum('SIM', 'NAO', 'ABSTENCAO', 'AUSENTE', 'OBSTRUCAO', 'PRESENTE_SEM_VOTO', name='tipovoto'), nullable=False),
    sa.Column('partido_na_epoca', sa.String(length=20), nullable=True),
    sa.Column('dados_brutos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['parlamentar_id'], ['parlamentares.id'], ),
    sa.ForeignKeyConstraint(['votacao_id'], ['votacoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('votacao_id', 'parlamentar_id', name='uq_voto_parlamentar')
    )
    op.create_index(op.f('ix_votos_parlamentares_parlamentar_id'), 'votos_parlamentares', ['parlamentar_id'], unique=False)
    op.create_index(op.f('ix_votos_parlamentares_votacao_id'), 'votos_parlamentares', ['votacao_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votos_parlamentares_votacao_id'), table_name='votos_parlamentares')
    op.drop_index(op.f('ix_votos_parlamentares_parlamentar_id'), table_name='votos_parlamentares')
    op.drop_table('votos_parlamentares')
    op.drop_index(op.f('ix_votacoes_id_externo'), table_name='votacoes')
    op.drop_table('votacoes')
    op.drop_index(op.f('ix_respostas_usuarios_usuario_id'), table_name='respostas_usuarios')
    op.drop_table('respostas_usuarios')
    op.drop_table('proposicoes_topicos')
    op.drop_index(op.f('ix_parlamentares_id_externo'), table_name='parlamentares')
    op.drop_table('parlamentares')
    op.drop_table('bloco_partido')
    op.drop_table('usuarios')
    op.drop_table('topicos')
    op.drop_index(op.f('ix_proposicoes_id_externo'), table_name='proposicoes')
    op.drop_table('proposicoes')
    op.drop_table('partidos')
    op.drop_table('blocos_parlamentares')
    # ### end Alembic commands ###
