"""add posicoes tables

Revision ID: 944ac0d79f97
Revises: a1b2c3d4e5f6
Create Date: 2026-03-20 12:54:51.528492
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '944ac0d79f97'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('tema', sa.String(length=50), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posicoes_slug'), 'posicoes', ['slug'], unique=True)
    op.create_table('posicao_proposicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posicao_id', sa.Integer(), nullable=False),
    sa.Column('proposicao_id', sa.Integer(), nullable=False),
    sa.Column('direcao', sa.Enum('SIM', 'NAO', name='direcaoposicao'), nullable=False),
    sa.ForeignKeyConstraint(['posicao_id'], ['posicoes.id'], ),
    sa.ForeignKeyConstraint(['proposicao_id'], ['proposicoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('posicao_id', 'proposicao_id', name='uq_posicao_proposicao')
    )
    op.create_index(op.f('ix_posicao_proposicoes_posicao_id'), 'posicao_proposicoes', ['posicao_id'], unique=False)
    op.create_table('respostas_posicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('posicao_id', sa.Integer(), nullable=False),
    sa.Column('voto', postgresql.ENUM('SIM', 'NAO', 'PULAR', name='votousuario', create_type=False), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['posicao_id'], ['posicoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'posicao_id', name='uq_resposta_posicao')
    )
    op.create_index(op.f('ix_respostas_posicoes_usuario_id'), 'respostas_posicoes', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_respostas_posicoes_usuario_id'), table_name='respostas_posicoes')
    op.drop_table('respostas_posicoes')
    op.drop_index(op.f('ix_posicao_proposicoes_posicao_id'), table_name='posicao_proposicoes')
    op.drop_table('posicao_proposicoes')
    op.drop_index(op.f('ix_posicoes_slug'), table_name='posicoes')
    op.drop_table('posicoes')
    # ### end Alembic commands ###
